name: space
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - openpyxl
  - streamlit
  - xgboost
  - ipykernel
  - joblib
  - pip
  - pip:
      - python-dotenv
      - langchain
      - langchain-community
      - langchain-groq
      - langgraph
      - sentence-transformers
      - faiss-cpu
